"""Report export utilities — Markdown and PDF.

Provides functions to export research reports in formatted Markdown
and styled PDF formats, including metadata headers, timestamps,
and proper section formatting.
"""

from __future__ import annotations

import io
from datetime import datetime, timezone

from exceptions import ExportError
from logger import get_logger
from models import CriticFeedback, PipelineResult, ResearchReport

logger = get_logger(__name__)


def export_markdown(result: PipelineResult) -> str:
    """Export a pipeline result as a formatted Markdown document.

    Includes a metadata header, the full report, critic feedback,
    and a generation timestamp.

    Args:
        result: Completed pipeline result.

    Returns:
        Complete Markdown string ready for download.

    Raises:
        ExportError: If no report is available to export.
    """
    if not result.report:
        raise ExportError("No report to export.", user_message="Cannot export — no report generated.")

    lines: list[str] = []

    # Metadata header
    lines.append(f"# Research Report: {result.topic}")
    lines.append("")
    lines.append(f"> Generated by ResearchMind on {result.report.generated_at.strftime('%Y-%m-%d %H:%M UTC')}")
    if result.duration_seconds:
        lines.append(f"> Pipeline completed in {result.duration_seconds:.1f} seconds")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Report body
    lines.append(result.report.content)
    lines.append("")

    # Critic feedback
    if result.feedback:
        lines.append("---")
        lines.append("")
        lines.append("## Critic Review")
        lines.append("")
        lines.append(result.feedback.content)
        lines.append("")

    # Footer
    lines.append("---")
    lines.append("")
    lines.append("*Generated by [ResearchMind](https://github.com/) — Multi-Agent AI Research System*")

    return "\n".join(lines)


def export_pdf(result: PipelineResult) -> bytes:
    """Export a pipeline result as a styled PDF document.

    Includes a title page, report sections, critic feedback,
    and a generation timestamp.

    Args:
        result: Completed pipeline result.

    Returns:
        PDF file as bytes, ready for download.

    Raises:
        ExportError: If fpdf2 is not installed or no report is available.
    """
    if not result.report:
        raise ExportError("No report to export.", user_message="Cannot export — no report generated.")

    try:
        from fpdf import FPDF
    except ImportError:
        raise ExportError(
            "fpdf2 is not installed. Run: uv add fpdf2",
            user_message="PDF export requires the fpdf2 package. Please install it.",
        )

    logger.info("Generating PDF for topic: %s", result.topic)

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=20)

    # ── Title page ────────────────────────────────────────────────────
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 28)
    pdf.ln(60)
    pdf.cell(0, 15, "Research Report", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(8)
    pdf.set_font("Helvetica", "", 14)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 10, result.topic, align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(20)
    pdf.set_font("Helvetica", "I", 10)
    pdf.cell(
        0, 8,
        f"Generated by ResearchMind on {result.report.generated_at.strftime('%Y-%m-%d %H:%M UTC')}",
        align="C", new_x="LMARGIN", new_y="NEXT",
    )
    if result.duration_seconds:
        pdf.cell(
            0, 8,
            f"Pipeline completed in {result.duration_seconds:.1f} seconds",
            align="C", new_x="LMARGIN", new_y="NEXT",
        )

    # ── Report content ────────────────────────────────────────────────
    pdf.add_page()
    pdf.set_text_color(0, 0, 0)

    for line in result.report.content.split("\n"):
        line = line.strip()
        if not line:
            pdf.ln(4)
            continue

        if line.startswith("## "):
            pdf.ln(6)
            pdf.set_font("Helvetica", "B", 14)
            # Encode to latin-1, replacing unsupported chars
            pdf.cell(0, 8, line[3:].encode("latin-1", "replace").decode("latin-1"),
                     new_x="LMARGIN", new_y="NEXT")
            pdf.ln(2)
        elif line.startswith("# "):
            pdf.set_font("Helvetica", "B", 16)
            pdf.cell(0, 10, line[2:].encode("latin-1", "replace").decode("latin-1"),
                     new_x="LMARGIN", new_y="NEXT")
            pdf.ln(3)
        elif line.startswith("- ") or line.startswith("* "):
            pdf.set_font("Helvetica", "", 10)
            bullet_text = f"  •  {line[2:]}"
            pdf.multi_cell(0, 6, bullet_text.encode("latin-1", "replace").decode("latin-1"))
        else:
            pdf.set_font("Helvetica", "", 10)
            pdf.multi_cell(0, 6, line.encode("latin-1", "replace").decode("latin-1"))

    # ── Critic feedback ───────────────────────────────────────────────
    if result.feedback:
        pdf.add_page()
        pdf.set_font("Helvetica", "B", 16)
        pdf.cell(0, 10, "Critic Review", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(4)

        for line in result.feedback.content.split("\n"):
            line = line.strip()
            if not line:
                pdf.ln(3)
                continue
            if line.startswith("**") and line.endswith("**"):
                pdf.set_font("Helvetica", "B", 11)
                pdf.cell(0, 7, line.strip("*").encode("latin-1", "replace").decode("latin-1"),
                         new_x="LMARGIN", new_y="NEXT")
            elif line.startswith("- "):
                pdf.set_font("Helvetica", "", 10)
                pdf.multi_cell(0, 6, f"  •  {line[2:]}".encode("latin-1", "replace").decode("latin-1"))
            else:
                pdf.set_font("Helvetica", "", 10)
                pdf.multi_cell(0, 6, line.encode("latin-1", "replace").decode("latin-1"))

    # ── Output ────────────────────────────────────────────────────────
    pdf_bytes = pdf.output()
    logger.info("PDF generated: %d bytes", len(pdf_bytes))
    return bytes(pdf_bytes)
